name: CD-FE

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: |
          cd client
          npm ci --only=production
          rm .gitignore
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: client
          single-commit: true
